### ISSUE TITLE
Переменная result вам нужна только на 8-ой строке - объявляйте ближе к контексту

### ISSUE THREAD

**Issue by coursar** [Eeenkeeei/02.Homework_wallpaper#1]
https://github.com/Eeenkeeei/02.Homework_wallpaper/blob/dfb6de781a3faf9e24e7e9ede87bf165cc21ab16/js/calculateWallpapers.js#L2-L10

2 строку убрать
8 должна выглядеть так:
```javascript
let result = countCanvas/countStripes; 
```

**Comment by Eeenkeeei** [comment]
fixed in 6de67e23f1bfa972e519c37b87670e3a254a4849

**Comment by coursar** [comment]
Закрывайте сразу таски сообщениями коммитов (см. видео)
